# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: "pretrained_embeddings_spacy"
case_sensitive: False
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.2
    fallback_nlu_action_name: "action_custom_fallback"
    deny_suggestion_intent_name: "out_of_scope"